### ISSUE TITLE
Typing letters instead of numbers

### ISSUE THREAD

**Issue by andrewten45** [andrewten45/playground#1]
Steps to reproduce:
1. Run program
2. Type in a alphabetical character like x

Expect: Repeat prompt
Actual: Program crashes

**Comment by andrewten45** [comment]
I've fixed it. I changed userIn from int to a new string variable called userString, initialized as empty. Now when alphabetical strings are entered, it simply repeats the prompt.

**Comment by schackbrian2012** [comment]
Cool!
