### ISSUE TITLE
Improvement to README.md

### ISSUE THREAD

**Issue by andrewten45** [andrewten45/playground#4]
Within the README file, it would be nice to have icons next to each bullet point. I have seen this type of feature on other repos, but was unsure on how to implement it with the markdown syntax.

**Comment by OlaPom** [comment]
Hello! You mean emojis? There is a list: https://gist.github.com/rxaviers/7360908

**Comment by andrewten45** [comment]
> Hello! You mean emojis? There is a list: https://gist.github.com/rxaviers/7360908

Thanks!
